import type { Food } from "./types";

export const FOODS: Food[] = [
  { id: "chicken-breast", name: "Chicken Breast", servingSize: "100g", calories: 165, protein: 31, carbs: 0, fat: 3.6 },
  { id: "white-rice", name: "White Rice", servingSize: "1 cup cooked", calories: 206, protein: 4.3, carbs: 45, fat: 0.4 },
  { id: "brown-rice", name: "Brown Rice", servingSize: "1 cup cooked", calories: 216, protein: 5, carbs: 45, fat: 1.8 },
  { id: "eggs", name: "Egg (large)", servingSize: "1 egg", calories: 72, protein: 6.3, carbs: 0.4, fat: 5 },
  { id: "banana", name: "Banana", servingSize: "1 medium", calories: 105, protein: 1.3, carbs: 27, fat: 0.4 },
  { id: "apple", name: "Apple", servingSize: "1 medium", calories: 95, protein: 0.5, carbs: 25, fat: 0.3 },
  { id: "whole-milk", name: "Whole Milk", servingSize: "1 cup (240ml)", calories: 149, protein: 8, carbs: 12, fat: 8 },
  { id: "greek-yogurt", name: "Greek Yogurt", servingSize: "170g", calories: 100, protein: 17, carbs: 6, fat: 0.7 },
  { id: "oats", name: "Oats", servingSize: "½ cup dry", calories: 154, protein: 5.4, carbs: 27, fat: 2.6 },
  { id: "salmon", name: "Salmon", servingSize: "100g", calories: 208, protein: 20, carbs: 0, fat: 13 },
  { id: "tuna", name: "Tuna (canned)", servingSize: "100g", calories: 128, protein: 28, carbs: 0, fat: 1 },
  { id: "bread", name: "Whole Wheat Bread", servingSize: "1 slice", calories: 70, protein: 4, carbs: 12, fat: 1 },
  { id: "pasta", name: "Pasta", servingSize: "1 cup cooked", calories: 220, protein: 8, carbs: 43, fat: 1.3 },
  { id: "broccoli", name: "Broccoli", servingSize: "1 cup", calories: 55, protein: 3.7, carbs: 11, fat: 0.6 },
  { id: "sweet-potato", name: "Sweet Potato", servingSize: "1 medium", calories: 103, protein: 2.3, carbs: 24, fat: 0.1 },
  { id: "avocado", name: "Avocado", servingSize: "½ fruit", calories: 161, protein: 2, carbs: 8.5, fat: 15 },
  { id: "almonds", name: "Almonds", servingSize: "1 oz (28g)", calories: 164, protein: 6, carbs: 6, fat: 14 },
  { id: "peanut-butter", name: "Peanut Butter", servingSize: "2 tbsp", calories: 190, protein: 8, carbs: 6, fat: 16 },
  { id: "cheddar-cheese", name: "Cheddar Cheese", servingSize: "1 oz (28g)", calories: 114, protein: 7, carbs: 0.4, fat: 9.4 },
  { id: "ground-beef", name: "Ground Beef (85% lean)", servingSize: "100g", calories: 215, protein: 26, carbs: 0, fat: 13 },
  { id: "protein-shake", name: "Protein Shake", servingSize: "1 scoop (30g)", calories: 120, protein: 25, carbs: 3, fat: 1.5 },
  { id: "orange-juice", name: "Orange Juice", servingSize: "1 cup (240ml)", calories: 112, protein: 1.7, carbs: 26, fat: 0.5 },
  { id: "spinach", name: "Spinach", servingSize: "1 cup raw", calories: 7, protein: 0.9, carbs: 1.1, fat: 0.1 },
  { id: "cottage-cheese", name: "Cottage Cheese", servingSize: "½ cup", calories: 110, protein: 12, carbs: 5, fat: 5 },
  { id: "black-beans", name: "Black Beans", servingSize: "½ cup cooked", calories: 114, protein: 7.6, carbs: 20, fat: 0.5 },
];
